server.port=${PORT:10000}

management.health.rabbit.enabled=${MANAGEMENT_HEALTH_RABBIT_ENABLED:false}
management.health.redis.enabled=${MANAGEMENT_HEALTH_REDIS_ENABLED:false}

spring.cache.type=${SPRING_CACHE_TYPE:simple}
spring.jpa.show-sql=false
