comment.client.auth-service-url=${AUTH_SERVICE_URL:https://codesync-auth-service.onrender.com}
comment.client.project-service-url=${PROJECT_SERVICE_URL:https://codesync-project-service.onrender.com}
comment.client.notification-service-url=${NOTIFICATION_SERVICE_URL:https://codesync-notification-service-4pcj.onrender.com}
