server.port=${PORT:10000}

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

spring.cloud.gateway.server.webflux.routes[0].uri=${GATEWAY_AUTH_SERVICE_URI:https://codesync-auth-service.onrender.com}
spring.cloud.gateway.server.webflux.routes[1].uri=${GATEWAY_PROJECT_SERVICE_URI:https://codesync-project-service.onrender.com}
spring.cloud.gateway.server.webflux.routes[2].uri=${GATEWAY_FILE_SERVICE_URI:https://codesync-file-service.onrender.com}
spring.cloud.gateway.server.webflux.routes[3].uri=${GATEWAY_COLLAB_SERVICE_URI:https://codesync-collab-service.onrender.com}
spring.cloud.gateway.server.webflux.routes[4].uri=${GATEWAY_VERSION_SERVICE_URI:https://codesync-version-service.onrender.com}
spring.cloud.gateway.server.webflux.routes[5].uri=${GATEWAY_COMMENT_SERVICE_URI:https://codesync-comment-service.onrender.com}
spring.cloud.gateway.server.webflux.routes[6].uri=${GATEWAY_NOTIFICATION_SERVICE_URI:https://codesync-notification-service-4pcj.onrender.com}
spring.cloud.gateway.server.webflux.routes[7].uri=${GATEWAY_EXECUTION_SERVICE_URI:https://codesync-execution-service.onrender.com}
