server.port=${SERVER_PORT:${PORT:10000}}

spring.datasource.url=${FILE_DATASOURCE_URL:${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:${DATABASE_URL:${DATASOURCE_URL:jdbc:mysql://${MYSQLHOST:${MYSQL_HOST:${DB_HOST:localhost}}}:${MYSQLPORT:${MYSQL_PORT:${DB_PORT:3306}}}/${MYSQLDATABASE:${MYSQL_DATABASE:${DB_NAME:file_db}}}?createDatabaseIfNotExist=true&sslMode=${MYSQL_SSL_MODE:${DB_SSL_MODE:REQUIRED}}&allowPublicKeyRetrieval=${MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL:${DB_ALLOW_PUBLIC_KEY_RETRIEVAL:true}}&serverTimezone=UTC}}}}}
spring.datasource.username=${FILE_DATASOURCE_USERNAME:${SPRING_DATASOURCE_USERNAME:${DATASOURCE_USERNAME:${DATABASE_USERNAME:${MYSQLUSER:${MYSQL_USER:${DB_USER:root}}}}}}}
spring.datasource.password=${FILE_DATASOURCE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:${DATASOURCE_PASSWORD:${DATABASE_PASSWORD:${MYSQLPASSWORD:${MYSQL_PASSWORD:${DB_PASSWORD:}}}}}}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.minimum-idle=0

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${FILE_DB_DDL_AUTO:none}
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.show-sql=false

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}

project.service.url=${PROJECT_SERVICE_URL:https://codesync-project-service.onrender.com}
file.client.version-service-url=${FILE_CLIENT_VERSION_SERVICE_URL:https://codesync-version-service.onrender.com}

management.health.db.enabled=false
management.health.rabbit.enabled=${MANAGEMENT_HEALTH_RABBIT_ENABLED:false}
management.health.redis.enabled=${MANAGEMENT_HEALTH_REDIS_ENABLED:false}
