spring.config.import=optional:file:../auth-service/.env[.properties]

spring.application.name=file-service
server.port=8083

spring.datasource.url=${FILE_DATASOURCE_URL:jdbc:mysql://localhost:3306/file_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${FILE_DATASOURCE_USERNAME:${DATASOURCE_USERNAME:root}}
spring.datasource.password=${FILE_DATASOURCE_PASSWORD:${DATASOURCE_PASSWORD:deepak@1234}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:mysupersecretkeymysupersecretkey1234567890}

project.service.url=${PROJECT_SERVICE_URL:http://localhost:8082}

server.error.include-message=always
server.error.include-binding-errors=always

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

management.endpoints.web.exposure.include=health,info

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
