auth.service.url=${AUTH_SERVICE_URL:https://codesync-auth-service.onrender.com}
project.client.notification-service-url=${PROJECT_CLIENT_NOTIFICATION_SERVICE_URL:https://codesync-notification-service-4pcj.onrender.com}
