codesync.services.project.base-url=${PROJECT_SERVICE_BASE_URL:https://codesync-project-service.onrender.com}
codesync.services.file.base-url=${FILE_SERVICE_BASE_URL:https://codesync-file-service.onrender.com}
