server.port=${PORT:10000}

spring.datasource.url=${DATASOURCE_URL:${DATABASE_URL:${JDBC_DATABASE_URL:${SPRING_DATASOURCE_URL:${COLLAB_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST:${MYSQL_HOST:${DB_HOST:localhost}}}:${MYSQLPORT:${MYSQL_PORT:${DB_PORT:3306}}}/${MYSQLDATABASE:${MYSQL_DATABASE:${DB_NAME:collab_db}}}?createDatabaseIfNotExist=true&sslMode=${MYSQL_SSL_MODE:${DB_SSL_MODE:REQUIRED}}&allowPublicKeyRetrieval=${MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL:${DB_ALLOW_PUBLIC_KEY_RETRIEVAL:true}}&serverTimezone=UTC}}}}}}
spring.datasource.username=${DATASOURCE_USERNAME:${DATABASE_USERNAME:${MYSQLUSER:${MYSQL_USER:${SPRING_DATASOURCE_USERNAME:${DB_USER:${COLLAB_DATASOURCE_USERNAME:root}}}}}}}
spring.datasource.password=${DATASOURCE_PASSWORD:${DATABASE_PASSWORD:${MYSQLPASSWORD:${MYSQL_PASSWORD:${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:${COLLAB_DATASOURCE_PASSWORD:}}}}}}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.minimum-idle=0

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${COLLAB_DB_DDL_AUTO:update}
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.show-sql=false

project.service.url=${PROJECT_SERVICE_URL:https://codesync-project-service.onrender.com}
file.service.url=${FILE_SERVICE_URL:https://codesync-file-service.onrender.com}

management.health.db.enabled=false
