server.port=${PORT:10000}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.minimum-idle=0

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${COLLAB_DB_DDL_AUTO:update}
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

project.service.url=${PROJECT_SERVICE_URL:https://codesync-project-service.onrender.com}
file.service.url=${FILE_SERVICE_URL:https://codesync-file-service.onrender.com}

management.health.db.enabled=false
